# Task 1

## Requirement
    1. Read in any image;
    2. Convert this image to YUV;
    3. Extract the Y channel (luminance);
    4. Convert the original image to grayscale (intensity);
    5. Show the two on the screen using OpenCV’s imshow function;
    6. Show the luminance on the screen side by side with the intensity
        using MatPlotLib’s subplot function (look this up)*.

In [19]:
# Import libraries

%matplotlib inline

import cv2 # The OpenCV library; install using `pip install opencv-contrib-python`
import numpy as np # Helpful when working with arrays; install using `pip install numpy`
from matplotlib import pyplot as plt # Good for graphing; install using `pip install matplotlib`
from matplotlib import image as image
import easygui # An easy-to-use file-picker; pip install easygui


In [20]:
# 1. Read the image

I = cv2.imread("res\phoenix.jpg") # Read Image
cv2.imshow("Original", I) # Show Image

# 2. Convert the colorspace from BGR to YUV

img_YUV = cv2.cvtColor(I, cv2.COLOR_BGR2YUV)
cv2.imshow("YUV", img_YUV) # Show Image

# 3. Extract the Y Channel - Luminance

y, u, v = cv2.split(img_YUV)
print(y)
cv2.imshow("Luminance", y)

# 4. Convert the original image to grayscale (intensity)

img_grayscale = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
cv2.imshow("Grayscale", img_grayscale) # Show Image

# 5. Show the two on the screen using OpenCV’s imshow function

numpy_horizontal = np.hstack((y, img_grayscale))
cv2.imshow("Mix", numpy_horizontal) # Show Image


# 6. Show the luminance on the screen side by side with the intensity
#   using MatPlotLib’s subplot function (look this up)*.

numpy_horizontal_yuv = np.hstack((y, u))
numpy_horizontal_yuv = np.hstack((numpy_horizontal_yuv,v))
cv2.imshow("YUV_Intensity", numpy_horizontal_yuv) # Show Image

key = cv2.waitKey(0) # Press a key before the image is disappeared
cv2.destroyAllWindows()

[[105 106 108 ...  99  99  99]
 [105 105 107 ...  99  99  99]
 [ 99 100 100 ...  99  99  99]
 ...
 [ 27  27  26 ...  50  50  50]
 [ 27  27  26 ...  49  49  49]
 [ 27  27  26 ...  49  49  49]]
